src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>A financially approved account with a customer # in an ERP</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SAP_Reference__c.object
<CustomObject>
    <description>This object is for maintaining the information about delivery terms, payment terms, Incoterms, and other tables of reference from Baan or SAP.</description>
    <fields>
        <fullName>Available_to_Sales_Area_Codes__c</fullName>
        <description>List of available sales area codes, separated by semicolons</description>
        <label>Available to Sales Area Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Type__c</fullName>
        <inlineHelpText>Enter the full name of the code type and then follow it with a - and a 2 letter code for the code type</inlineHelpText>
        <label>Code Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Group - CG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Language - CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Priority - DP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery_Terms_DT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incoterm - IC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Series - OS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Type - OT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment_Terms_PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Group - PG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region Code - RC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales District - SD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Office - SO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping Condition - SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terms of Payment - TP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Zone - TZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse Codes - WC</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SAP Reference</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP References</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CustomLookUpController.cls
public class CustomLookUpController {
    
    @AuraEnabled
    public static List<SObject> fetchLookupValues(String searchKeyword, String objectName, String filter){
        List<SObject> returnList = new List<SObject>();
        String searchKey = searchKeyword + '%';
        String areaCode = '%'+filter.removeStartIgnoreCase('Sales Office')+'%';
        String emeaAccountId = Label.EnerSys_EMEA_Account;
        
        String sQuery = getQuery(searchKeyword, objectName, filter);
        
        List<SObject> results = Database.query(sQuery);
        
        for(SObject obj : results){
            returnList.add(obj);
        }
        
        return returnList;
    }
	
    @testVisible
    private static String getQuery(String searchKeyWord, String objectName, String filter ){
        String sQuery;
        
        String searchKey = searchKeyWord + '%';
        
        if(filter=='Sales District'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Sales District - SD\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey) ORDER BY NAME ASC LIMIT 8';
        }
        if(filter=='Customer Group'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Customer Group - CG\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey) ORDER BY NAME ASC LIMIT 8 ';
        }
        if(filter=='Terms Of Payment'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Terms of Payment - TP\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey) ORDER BY NAME ASC LIMIT 8 ';
        }
        if(filter=='Price Group'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Price Group - PG\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey) ORDER BY NAME ASC LIMIT 8 ';
        }
        if(filter=='Incoterm'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Incoterm - IC\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey)  ORDER BY NAME ASC LIMIT 8 ';
        }
        if(filter=='Delivery Priority'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Delivery Priority - DP\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey)  ORDER BY NAME ASC LIMIT 8 ';
        }
        if(filter=='Shipping Conditions'){
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c = \'Shipping Condition - SC\' AND (Name LIKE :searchKey OR Code__c LIKE :searchKey) ORDER BY NAME ASC LIMIT 8 ';
        }
        if(filter=='Contact'){
            return 'Select Id, Name from Contact WHERE Name Like :searchKey AND AccountId = :emeaAccountId ORDER BY NAME ASC LIMIT 10 ';
        }
        if(filter.startsWithIgnoreCase('Sales Office')){
            String areaCode = filter.remove('Sales Office')+'%';
            return 'Select Id, Name, Code__c FROM SAP_Reference__c WHERE Code_Type__c= \'Sales Office - SO\' AND Available_to_Sales_Area_Codes__c LIKE :areaCode AND (Name LIKE :searchKey OR Code__c LIKE :searchKey) ORDER BY NAME ASC LIMIT 8 ';
        }
        
        //Set<String> genericQueryObjects = new Set<String>({'Account', 'Contact', 'Sales_Area__c'})
        
        return  'Select Id, Name from ' +objectName + ' where Name LIKE :searchKey order by createdDate DESC limit 5';
        
    }
}